// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    
    // New 7-Part Structure (Feature: 004-complete-textbook-restructure)
    {
      type: 'category',
      label: 'Part 1: Foundations of Physical AI',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part-01-foundations'}],
    },
    
    {
      type: 'category',
      label: 'Part 2: ROS 2 Ecosystem',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part-02-ros2-ecosystem'}],
    },
    
    {
      type: 'category',
      label: 'Part 3: Simulation Environments',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part-03-simulation-environments'}],
    },
    
    {
      type: 'category',
      label: 'Part 4: NVIDIA Isaac Platform',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part-04-nvidia-isaac-platform'}],
    },
    
    {
      type: 'category',
      label: 'Part 5: Humanoid Development',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part-05-humanoid-development'}],
    },
    
    {
      type: 'category',
      label: 'Part 6: Conversational Robotics',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part-06-conversational-robotics'}],
    },
    
    {
      type: 'category',
      label: 'Part 7: Capstone Project',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'part-07-capstone-project'}],
    },
    
    // Legacy Structure (kept for reference during migration)
    /*
    {
      type: 'category',
      label: 'Weeks 1-2: Foundations of Physical AI',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'week-01-02'}],
    },
    
    {
      type: 'category',
      label: 'Weeks 3-5: ROS 2 and Robot Programming',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'week-03-05'}],
    },
    
    {
      type: 'category',
      label: 'Weeks 6-7: Perception Systems',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'week-06-07'}],
    },
    
    {
      type: 'category',
      label: 'Weeks 8-10: Motion Planning and Control',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'week-08-10'}],
    },
    
    {
      type: 'category',
      label: 'Weeks 11-12: Humanoid Robotics',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'week-11-12'}],
    },
    
    {
      type: 'category',
      label: 'Week 13: Simulation and Integration',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'week-13'}],
    },
    */
    
    'assessments',
    
    {
      type: 'category',
      label: 'Appendices',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'appendices'}],
    },
  ],
};

export default sidebars;
