// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    
    {
      type: 'category',
      label: 'Weeks 1-2: Foundations of Physical AI',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'week-01-02'}],
    },
    
    {
      type: 'category',
      label: 'Weeks 3-5: ROS 2 and Robot Programming',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'week-03-05'}],
    },
    
    {
      type: 'category',
      label: 'Weeks 6-7: Perception Systems',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'week-06-07'}],
    },
    
    {
      type: 'category',
      label: 'Weeks 8-10: Motion Planning and Control',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'week-08-10'}],
    },
    
    {
      type: 'category',
      label: 'Weeks 11-12: Humanoid Robotics',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'week-11-12'}],
    },
    
    {
      type: 'category',
      label: 'Week 13: Simulation and Integration',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'week-13'}],
    },
    
    'assessments',
    
    {
      type: 'category',
      label: 'Appendix',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'appendix'}],
    },
  ],
};

export default sidebars;
